name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20.19.2-alpine3.21
          cache: "npm"
      - run: npm install
      - run: npm run test
